import './globals.css'
import Animate from 'components/Animation'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Animate>
        {children}
        </Animate>
      </body>
    </html>
  )
}
