import 'styles/globals.scss';
import Provider from 'components/Animation/Provider';
import StyledJsxRegistry from './registry';
import Animation from 'components/Animation';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <StyledJsxRegistry>
            <Animation>{children}</Animation>
          </StyledJsxRegistry>
        </Provider>
      </body>
    </html>
  );
}
